### ISSUE TITLE
Replicate part of master

### ISSUE THREAD

**Issue by carboniris** [dominictarr/level-master#3]
Is it possible to run some kind of query, such as from [map-reduce](https://github.com/dominictarr/map-reduce), [level-query](https://github.com/substack/level-query), etc, and only replicate that query's results from the master to the slave?

**Comment by dominictarr** [comment]
that isn't implemented here, but it certainly is possible. I'm not maintaining this module anymore (I have not used it in a long time) I am now working on a different approach to node.js databases that makes this sort of thing much easier http://github.com/flumedb

Working on things like this module eventually showed me that we where doing it all wrong with leveldb. This module works by creating an internal log, then streaming that to peers. Every database has a log inside of it, but usually the user is not able to query the log! Flume is based around the idea of a log (which is also the main storage of the database) and then various views that stream off that log.

**Comment by carboniris** [comment]
Hmm. I'll head over to flumedb, then, it looks like a much better fit.
